name: macos

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run the tests
      run: |
        pip install --user . pytest
        export PATH=~/.local/bin:$PATH
        pytest .

